//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ODS_Model", "FK_ODS_Users_ODS_Roles", "ODS_Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminTools.DataModel.ODS_Roles), "ODS_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminTools.DataModel.ODS_Users), true)]
[assembly: EdmRelationshipAttribute("ODS_Model", "FK_ODS_Address_ODS_Uchs", "ODS_Uchs", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminTools.DataModel.ODS_Uchs), "ODS_Address", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminTools.DataModel.ODS_Address), true)]
[assembly: EdmRelationshipAttribute("ODS_Model", "FK_ODS_Clients_ODS_Address", "ODS_Address", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminTools.DataModel.ODS_Address), "ODS_Clients", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminTools.DataModel.ODS_Clients), true)]
[assembly: EdmRelationshipAttribute("ODS_Model", "FK_ODS_Journals_ODS_Address", "ODS_Address", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminTools.DataModel.ODS_Address), "ODS_Journals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminTools.DataModel.ODS_Journals), true)]
[assembly: EdmRelationshipAttribute("ODS_Model", "FK_ODS_Journals_ODS_Clients", "ODS_Clients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminTools.DataModel.ODS_Clients), "ODS_Journals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminTools.DataModel.ODS_Journals), true)]
[assembly: EdmRelationshipAttribute("ODS_Model", "FK_ODS_Journals_ODS_Damages", "ODS_Damages", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AdminTools.DataModel.ODS_Damages), "ODS_Journals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminTools.DataModel.ODS_Journals), true)]
[assembly: EdmRelationshipAttribute("ODS_Model", "FK_ODS_Journals_ODS_Powers", "ODS_Powers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AdminTools.DataModel.ODS_Powers), "ODS_Journals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminTools.DataModel.ODS_Journals), true)]
[assembly: EdmRelationshipAttribute("ODS_Model", "FK_ODS_Journals_ODS_Problems", "ODS_Problems", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminTools.DataModel.ODS_Problems), "ODS_Journals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminTools.DataModel.ODS_Journals), true)]
[assembly: EdmRelationshipAttribute("ODS_Model", "FK_ODS_Journals_ODS_Users", "ODS_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminTools.DataModel.ODS_Users), "ODS_Journals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminTools.DataModel.ODS_Journals), true)]

#endregion

namespace AdminTools.DataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ODS_db : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ODS_db object using the connection string found in the 'ODS_db' section of the application configuration file.
        /// </summary>
        public ODS_db() : base("name=ODS_db", "ODS_db")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ODS_db object.
        /// </summary>
        public ODS_db(string connectionString) : base(connectionString, "ODS_db")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ODS_db object.
        /// </summary>
        public ODS_db(EntityConnection connection) : base(connection, "ODS_db")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ODS_Roles> ODS_Roles
        {
            get
            {
                if ((_ODS_Roles == null))
                {
                    _ODS_Roles = base.CreateObjectSet<ODS_Roles>("ODS_Roles");
                }
                return _ODS_Roles;
            }
        }
        private ObjectSet<ODS_Roles> _ODS_Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ODS_Users> ODS_Users
        {
            get
            {
                if ((_ODS_Users == null))
                {
                    _ODS_Users = base.CreateObjectSet<ODS_Users>("ODS_Users");
                }
                return _ODS_Users;
            }
        }
        private ObjectSet<ODS_Users> _ODS_Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ODS_Address> ODS_Address
        {
            get
            {
                if ((_ODS_Address == null))
                {
                    _ODS_Address = base.CreateObjectSet<ODS_Address>("ODS_Address");
                }
                return _ODS_Address;
            }
        }
        private ObjectSet<ODS_Address> _ODS_Address;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ODS_Damages> ODS_Damages
        {
            get
            {
                if ((_ODS_Damages == null))
                {
                    _ODS_Damages = base.CreateObjectSet<ODS_Damages>("ODS_Damages");
                }
                return _ODS_Damages;
            }
        }
        private ObjectSet<ODS_Damages> _ODS_Damages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ODS_Powers> ODS_Powers
        {
            get
            {
                if ((_ODS_Powers == null))
                {
                    _ODS_Powers = base.CreateObjectSet<ODS_Powers>("ODS_Powers");
                }
                return _ODS_Powers;
            }
        }
        private ObjectSet<ODS_Powers> _ODS_Powers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ODS_Problems> ODS_Problems
        {
            get
            {
                if ((_ODS_Problems == null))
                {
                    _ODS_Problems = base.CreateObjectSet<ODS_Problems>("ODS_Problems");
                }
                return _ODS_Problems;
            }
        }
        private ObjectSet<ODS_Problems> _ODS_Problems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ODS_Uchs> ODS_Uchs
        {
            get
            {
                if ((_ODS_Uchs == null))
                {
                    _ODS_Uchs = base.CreateObjectSet<ODS_Uchs>("ODS_Uchs");
                }
                return _ODS_Uchs;
            }
        }
        private ObjectSet<ODS_Uchs> _ODS_Uchs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ODS_Clients> ODS_Clients
        {
            get
            {
                if ((_ODS_Clients == null))
                {
                    _ODS_Clients = base.CreateObjectSet<ODS_Clients>("ODS_Clients");
                }
                return _ODS_Clients;
            }
        }
        private ObjectSet<ODS_Clients> _ODS_Clients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ODS_Journals> ODS_Journals
        {
            get
            {
                if ((_ODS_Journals == null))
                {
                    _ODS_Journals = base.CreateObjectSet<ODS_Journals>("ODS_Journals");
                }
                return _ODS_Journals;
            }
        }
        private ObjectSet<ODS_Journals> _ODS_Journals;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ODS_Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToODS_Roles(ODS_Roles oDS_Roles)
        {
            base.AddObject("ODS_Roles", oDS_Roles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ODS_Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToODS_Users(ODS_Users oDS_Users)
        {
            base.AddObject("ODS_Users", oDS_Users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ODS_Address EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToODS_Address(ODS_Address oDS_Address)
        {
            base.AddObject("ODS_Address", oDS_Address);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ODS_Damages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToODS_Damages(ODS_Damages oDS_Damages)
        {
            base.AddObject("ODS_Damages", oDS_Damages);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ODS_Powers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToODS_Powers(ODS_Powers oDS_Powers)
        {
            base.AddObject("ODS_Powers", oDS_Powers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ODS_Problems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToODS_Problems(ODS_Problems oDS_Problems)
        {
            base.AddObject("ODS_Problems", oDS_Problems);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ODS_Uchs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToODS_Uchs(ODS_Uchs oDS_Uchs)
        {
            base.AddObject("ODS_Uchs", oDS_Uchs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ODS_Clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToODS_Clients(ODS_Clients oDS_Clients)
        {
            base.AddObject("ODS_Clients", oDS_Clients);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ODS_Journals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToODS_Journals(ODS_Journals oDS_Journals)
        {
            base.AddObject("ODS_Journals", oDS_Journals);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ODS_Model", Name="ODS_Address")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ODS_Address : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ODS_Address object.
        /// </summary>
        /// <param name="addressId">Initial value of the AddressId property.</param>
        /// <param name="uchId">Initial value of the UchId property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static ODS_Address CreateODS_Address(global::System.Int32 addressId, global::System.Int32 uchId, global::System.String address)
        {
            ODS_Address oDS_Address = new ODS_Address();
            oDS_Address.AddressId = addressId;
            oDS_Address.UchId = uchId;
            oDS_Address.Address = address;
            return oDS_Address;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                if (_AddressId != value)
                {
                    OnAddressIdChanging(value);
                    ReportPropertyChanging("AddressId");
                    _AddressId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AddressId");
                    OnAddressIdChanged();
                }
            }
        }
        private global::System.Int32 _AddressId;
        partial void OnAddressIdChanging(global::System.Int32 value);
        partial void OnAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UchId
        {
            get
            {
                return _UchId;
            }
            set
            {
                OnUchIdChanging(value);
                ReportPropertyChanging("UchId");
                _UchId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UchId");
                OnUchIdChanged();
            }
        }
        private global::System.Int32 _UchId;
        partial void OnUchIdChanging(global::System.Int32 value);
        partial void OnUchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Address_ODS_Uchs", "ODS_Uchs")]
        public ODS_Uchs ODS_Uchs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Uchs>("ODS_Model.FK_ODS_Address_ODS_Uchs", "ODS_Uchs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Uchs>("ODS_Model.FK_ODS_Address_ODS_Uchs", "ODS_Uchs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ODS_Uchs> ODS_UchsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Uchs>("ODS_Model.FK_ODS_Address_ODS_Uchs", "ODS_Uchs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ODS_Uchs>("ODS_Model.FK_ODS_Address_ODS_Uchs", "ODS_Uchs", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Clients_ODS_Address", "ODS_Clients")]
        public EntityCollection<ODS_Clients> ODS_Clients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ODS_Clients>("ODS_Model.FK_ODS_Clients_ODS_Address", "ODS_Clients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ODS_Clients>("ODS_Model.FK_ODS_Clients_ODS_Address", "ODS_Clients", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Address", "ODS_Journals")]
        public EntityCollection<ODS_Journals> ODS_Journals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Address", "ODS_Journals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Address", "ODS_Journals", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ODS_Model", Name="ODS_Clients")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ODS_Clients : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ODS_Clients object.
        /// </summary>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="clientFIO">Initial value of the ClientFIO property.</param>
        /// <param name="clientPhone">Initial value of the ClientPhone property.</param>
        /// <param name="clientHomeNum">Initial value of the ClientHomeNum property.</param>
        /// <param name="addressId">Initial value of the AddressId property.</param>
        /// <param name="liter">Initial value of the Liter property.</param>
        /// <param name="entrance">Initial value of the Entrance property.</param>
        /// <param name="room">Initial value of the Room property.</param>
        public static ODS_Clients CreateODS_Clients(global::System.Int32 clientId, global::System.String clientFIO, global::System.String clientPhone, global::System.Int32 clientHomeNum, global::System.Int32 addressId, global::System.String liter, global::System.Int32 entrance, global::System.Int32 room)
        {
            ODS_Clients oDS_Clients = new ODS_Clients();
            oDS_Clients.ClientId = clientId;
            oDS_Clients.ClientFIO = clientFIO;
            oDS_Clients.ClientPhone = clientPhone;
            oDS_Clients.ClientHomeNum = clientHomeNum;
            oDS_Clients.AddressId = addressId;
            oDS_Clients.Liter = liter;
            oDS_Clients.Entrance = entrance;
            oDS_Clients.Room = room;
            return oDS_Clients;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                if (_ClientId != value)
                {
                    OnClientIdChanging(value);
                    ReportPropertyChanging("ClientId");
                    _ClientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClientId");
                    OnClientIdChanged();
                }
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientFIO
        {
            get
            {
                return _ClientFIO;
            }
            set
            {
                OnClientFIOChanging(value);
                ReportPropertyChanging("ClientFIO");
                _ClientFIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientFIO");
                OnClientFIOChanged();
            }
        }
        private global::System.String _ClientFIO;
        partial void OnClientFIOChanging(global::System.String value);
        partial void OnClientFIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientPhone
        {
            get
            {
                return _ClientPhone;
            }
            set
            {
                OnClientPhoneChanging(value);
                ReportPropertyChanging("ClientPhone");
                _ClientPhone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientPhone");
                OnClientPhoneChanged();
            }
        }
        private global::System.String _ClientPhone;
        partial void OnClientPhoneChanging(global::System.String value);
        partial void OnClientPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientHomeNum
        {
            get
            {
                return _ClientHomeNum;
            }
            set
            {
                OnClientHomeNumChanging(value);
                ReportPropertyChanging("ClientHomeNum");
                _ClientHomeNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientHomeNum");
                OnClientHomeNumChanged();
            }
        }
        private global::System.Int32 _ClientHomeNum;
        partial void OnClientHomeNumChanging(global::System.Int32 value);
        partial void OnClientHomeNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                OnAddressIdChanging(value);
                ReportPropertyChanging("AddressId");
                _AddressId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddressId");
                OnAddressIdChanged();
            }
        }
        private global::System.Int32 _AddressId;
        partial void OnAddressIdChanging(global::System.Int32 value);
        partial void OnAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Liter
        {
            get
            {
                return _Liter;
            }
            set
            {
                OnLiterChanging(value);
                ReportPropertyChanging("Liter");
                _Liter = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Liter");
                OnLiterChanged();
            }
        }
        private global::System.String _Liter;
        partial void OnLiterChanging(global::System.String value);
        partial void OnLiterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Entrance
        {
            get
            {
                return _Entrance;
            }
            set
            {
                OnEntranceChanging(value);
                ReportPropertyChanging("Entrance");
                _Entrance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Entrance");
                OnEntranceChanged();
            }
        }
        private global::System.Int32 _Entrance;
        partial void OnEntranceChanging(global::System.Int32 value);
        partial void OnEntranceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Room
        {
            get
            {
                return _Room;
            }
            set
            {
                OnRoomChanging(value);
                ReportPropertyChanging("Room");
                _Room = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Room");
                OnRoomChanged();
            }
        }
        private global::System.Int32 _Room;
        partial void OnRoomChanging(global::System.Int32 value);
        partial void OnRoomChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Clients_ODS_Address", "ODS_Address")]
        public ODS_Address ODS_Address
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Address>("ODS_Model.FK_ODS_Clients_ODS_Address", "ODS_Address").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Address>("ODS_Model.FK_ODS_Clients_ODS_Address", "ODS_Address").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ODS_Address> ODS_AddressReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Address>("ODS_Model.FK_ODS_Clients_ODS_Address", "ODS_Address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ODS_Address>("ODS_Model.FK_ODS_Clients_ODS_Address", "ODS_Address", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Clients", "ODS_Journals")]
        public EntityCollection<ODS_Journals> ODS_Journals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Clients", "ODS_Journals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Clients", "ODS_Journals", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ODS_Model", Name="ODS_Damages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ODS_Damages : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ODS_Damages object.
        /// </summary>
        /// <param name="damageId">Initial value of the DamageId property.</param>
        /// <param name="damage">Initial value of the Damage property.</param>
        public static ODS_Damages CreateODS_Damages(global::System.Int32 damageId, global::System.String damage)
        {
            ODS_Damages oDS_Damages = new ODS_Damages();
            oDS_Damages.DamageId = damageId;
            oDS_Damages.Damage = damage;
            return oDS_Damages;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DamageId
        {
            get
            {
                return _DamageId;
            }
            set
            {
                if (_DamageId != value)
                {
                    OnDamageIdChanging(value);
                    ReportPropertyChanging("DamageId");
                    _DamageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DamageId");
                    OnDamageIdChanged();
                }
            }
        }
        private global::System.Int32 _DamageId;
        partial void OnDamageIdChanging(global::System.Int32 value);
        partial void OnDamageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Damage
        {
            get
            {
                return _Damage;
            }
            set
            {
                OnDamageChanging(value);
                ReportPropertyChanging("Damage");
                _Damage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Damage");
                OnDamageChanged();
            }
        }
        private global::System.String _Damage;
        partial void OnDamageChanging(global::System.String value);
        partial void OnDamageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Damages", "ODS_Journals")]
        public EntityCollection<ODS_Journals> ODS_Journals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Damages", "ODS_Journals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Damages", "ODS_Journals", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ODS_Model", Name="ODS_Journals")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ODS_Journals : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ODS_Journals object.
        /// </summary>
        /// <param name="journalId">Initial value of the JournalId property.</param>
        /// <param name="entryId">Initial value of the EntryId property.</param>
        /// <param name="recieveDate">Initial value of the RecieveDate property.</param>
        /// <param name="recieveTime">Initial value of the RecieveTime property.</param>
        /// <param name="addressId">Initial value of the AddressId property.</param>
        /// <param name="problemId">Initial value of the ProblemId property.</param>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="clientTelephone">Initial value of the ClientTelephone property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static ODS_Journals CreateODS_Journals(global::System.Guid journalId, global::System.Int32 entryId, global::System.DateTime recieveDate, global::System.TimeSpan recieveTime, global::System.Int32 addressId, global::System.Int32 problemId, global::System.Int32 clientId, global::System.String clientTelephone, global::System.Int32 userId)
        {
            ODS_Journals oDS_Journals = new ODS_Journals();
            oDS_Journals.JournalId = journalId;
            oDS_Journals.EntryId = entryId;
            oDS_Journals.RecieveDate = recieveDate;
            oDS_Journals.RecieveTime = recieveTime;
            oDS_Journals.AddressId = addressId;
            oDS_Journals.ProblemId = problemId;
            oDS_Journals.ClientId = clientId;
            oDS_Journals.ClientTelephone = clientTelephone;
            oDS_Journals.UserId = userId;
            return oDS_Journals;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid JournalId
        {
            get
            {
                return _JournalId;
            }
            set
            {
                if (_JournalId != value)
                {
                    OnJournalIdChanging(value);
                    ReportPropertyChanging("JournalId");
                    _JournalId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("JournalId");
                    OnJournalIdChanged();
                }
            }
        }
        private global::System.Guid _JournalId;
        partial void OnJournalIdChanging(global::System.Guid value);
        partial void OnJournalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EntryId
        {
            get
            {
                return _EntryId;
            }
            set
            {
                OnEntryIdChanging(value);
                ReportPropertyChanging("EntryId");
                _EntryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryId");
                OnEntryIdChanged();
            }
        }
        private global::System.Int32 _EntryId;
        partial void OnEntryIdChanging(global::System.Int32 value);
        partial void OnEntryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RecieveDate
        {
            get
            {
                return _RecieveDate;
            }
            set
            {
                OnRecieveDateChanging(value);
                ReportPropertyChanging("RecieveDate");
                _RecieveDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecieveDate");
                OnRecieveDateChanged();
            }
        }
        private global::System.DateTime _RecieveDate;
        partial void OnRecieveDateChanging(global::System.DateTime value);
        partial void OnRecieveDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan RecieveTime
        {
            get
            {
                return _RecieveTime;
            }
            set
            {
                OnRecieveTimeChanging(value);
                ReportPropertyChanging("RecieveTime");
                _RecieveTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecieveTime");
                OnRecieveTimeChanged();
            }
        }
        private global::System.TimeSpan _RecieveTime;
        partial void OnRecieveTimeChanging(global::System.TimeSpan value);
        partial void OnRecieveTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                OnAddressIdChanging(value);
                ReportPropertyChanging("AddressId");
                _AddressId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddressId");
                OnAddressIdChanged();
            }
        }
        private global::System.Int32 _AddressId;
        partial void OnAddressIdChanging(global::System.Int32 value);
        partial void OnAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProblemId
        {
            get
            {
                return _ProblemId;
            }
            set
            {
                OnProblemIdChanging(value);
                ReportPropertyChanging("ProblemId");
                _ProblemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProblemId");
                OnProblemIdChanged();
            }
        }
        private global::System.Int32 _ProblemId;
        partial void OnProblemIdChanging(global::System.Int32 value);
        partial void OnProblemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                OnClientIdChanging(value);
                ReportPropertyChanging("ClientId");
                _ClientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientId");
                OnClientIdChanged();
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientTelephone
        {
            get
            {
                return _ClientTelephone;
            }
            set
            {
                OnClientTelephoneChanging(value);
                ReportPropertyChanging("ClientTelephone");
                _ClientTelephone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientTelephone");
                OnClientTelephoneChanged();
            }
        }
        private global::System.String _ClientTelephone;
        partial void OnClientTelephoneChanging(global::System.String value);
        partial void OnClientTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateComplete
        {
            get
            {
                return _DateComplete;
            }
            set
            {
                OnDateCompleteChanging(value);
                ReportPropertyChanging("DateComplete");
                _DateComplete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateComplete");
                OnDateCompleteChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateComplete;
        partial void OnDateCompleteChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCompleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> TimeComplete
        {
            get
            {
                return _TimeComplete;
            }
            set
            {
                OnTimeCompleteChanging(value);
                ReportPropertyChanging("TimeComplete");
                _TimeComplete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeComplete");
                OnTimeCompleteChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _TimeComplete;
        partial void OnTimeCompleteChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTimeCompleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PowerId
        {
            get
            {
                return _PowerId;
            }
            set
            {
                OnPowerIdChanging(value);
                ReportPropertyChanging("PowerId");
                _PowerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PowerId");
                OnPowerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PowerId;
        partial void OnPowerIdChanging(Nullable<global::System.Int32> value);
        partial void OnPowerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DamageId
        {
            get
            {
                return _DamageId;
            }
            set
            {
                OnDamageIdChanging(value);
                ReportPropertyChanging("DamageId");
                _DamageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DamageId");
                OnDamageIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DamageId;
        partial void OnDamageIdChanging(Nullable<global::System.Int32> value);
        partial void OnDamageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ComplUserId
        {
            get
            {
                return _ComplUserId;
            }
            set
            {
                OnComplUserIdChanging(value);
                ReportPropertyChanging("ComplUserId");
                _ComplUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComplUserId");
                OnComplUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ComplUserId;
        partial void OnComplUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnComplUserIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Address", "ODS_Address")]
        public ODS_Address ODS_Address
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Address>("ODS_Model.FK_ODS_Journals_ODS_Address", "ODS_Address").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Address>("ODS_Model.FK_ODS_Journals_ODS_Address", "ODS_Address").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ODS_Address> ODS_AddressReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Address>("ODS_Model.FK_ODS_Journals_ODS_Address", "ODS_Address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ODS_Address>("ODS_Model.FK_ODS_Journals_ODS_Address", "ODS_Address", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Clients", "ODS_Clients")]
        public ODS_Clients ODS_Clients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Clients>("ODS_Model.FK_ODS_Journals_ODS_Clients", "ODS_Clients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Clients>("ODS_Model.FK_ODS_Journals_ODS_Clients", "ODS_Clients").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ODS_Clients> ODS_ClientsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Clients>("ODS_Model.FK_ODS_Journals_ODS_Clients", "ODS_Clients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ODS_Clients>("ODS_Model.FK_ODS_Journals_ODS_Clients", "ODS_Clients", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Damages", "ODS_Damages")]
        public ODS_Damages ODS_Damages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Damages>("ODS_Model.FK_ODS_Journals_ODS_Damages", "ODS_Damages").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Damages>("ODS_Model.FK_ODS_Journals_ODS_Damages", "ODS_Damages").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ODS_Damages> ODS_DamagesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Damages>("ODS_Model.FK_ODS_Journals_ODS_Damages", "ODS_Damages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ODS_Damages>("ODS_Model.FK_ODS_Journals_ODS_Damages", "ODS_Damages", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Powers", "ODS_Powers")]
        public ODS_Powers ODS_Powers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Powers>("ODS_Model.FK_ODS_Journals_ODS_Powers", "ODS_Powers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Powers>("ODS_Model.FK_ODS_Journals_ODS_Powers", "ODS_Powers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ODS_Powers> ODS_PowersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Powers>("ODS_Model.FK_ODS_Journals_ODS_Powers", "ODS_Powers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ODS_Powers>("ODS_Model.FK_ODS_Journals_ODS_Powers", "ODS_Powers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Problems", "ODS_Problems")]
        public ODS_Problems ODS_Problems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Problems>("ODS_Model.FK_ODS_Journals_ODS_Problems", "ODS_Problems").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Problems>("ODS_Model.FK_ODS_Journals_ODS_Problems", "ODS_Problems").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ODS_Problems> ODS_ProblemsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Problems>("ODS_Model.FK_ODS_Journals_ODS_Problems", "ODS_Problems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ODS_Problems>("ODS_Model.FK_ODS_Journals_ODS_Problems", "ODS_Problems", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Users", "ODS_Users")]
        public ODS_Users ODS_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Users>("ODS_Model.FK_ODS_Journals_ODS_Users", "ODS_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Users>("ODS_Model.FK_ODS_Journals_ODS_Users", "ODS_Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ODS_Users> ODS_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Users>("ODS_Model.FK_ODS_Journals_ODS_Users", "ODS_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ODS_Users>("ODS_Model.FK_ODS_Journals_ODS_Users", "ODS_Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ODS_Model", Name="ODS_Powers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ODS_Powers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ODS_Powers object.
        /// </summary>
        /// <param name="powerId">Initial value of the PowerId property.</param>
        public static ODS_Powers CreateODS_Powers(global::System.Int32 powerId)
        {
            ODS_Powers oDS_Powers = new ODS_Powers();
            oDS_Powers.PowerId = powerId;
            return oDS_Powers;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PowerId
        {
            get
            {
                return _PowerId;
            }
            set
            {
                if (_PowerId != value)
                {
                    OnPowerIdChanging(value);
                    ReportPropertyChanging("PowerId");
                    _PowerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PowerId");
                    OnPowerIdChanged();
                }
            }
        }
        private global::System.Int32 _PowerId;
        partial void OnPowerIdChanging(global::System.Int32 value);
        partial void OnPowerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Power
        {
            get
            {
                return _Power;
            }
            set
            {
                OnPowerChanging(value);
                ReportPropertyChanging("Power");
                _Power = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Power");
                OnPowerChanged();
            }
        }
        private global::System.String _Power;
        partial void OnPowerChanging(global::System.String value);
        partial void OnPowerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Powers", "ODS_Journals")]
        public EntityCollection<ODS_Journals> ODS_Journals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Powers", "ODS_Journals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Powers", "ODS_Journals", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ODS_Model", Name="ODS_Problems")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ODS_Problems : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ODS_Problems object.
        /// </summary>
        /// <param name="problemId">Initial value of the ProblemId property.</param>
        public static ODS_Problems CreateODS_Problems(global::System.Int32 problemId)
        {
            ODS_Problems oDS_Problems = new ODS_Problems();
            oDS_Problems.ProblemId = problemId;
            return oDS_Problems;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProblemId
        {
            get
            {
                return _ProblemId;
            }
            set
            {
                if (_ProblemId != value)
                {
                    OnProblemIdChanging(value);
                    ReportPropertyChanging("ProblemId");
                    _ProblemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProblemId");
                    OnProblemIdChanged();
                }
            }
        }
        private global::System.Int32 _ProblemId;
        partial void OnProblemIdChanging(global::System.Int32 value);
        partial void OnProblemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Problem
        {
            get
            {
                return _Problem;
            }
            set
            {
                OnProblemChanging(value);
                ReportPropertyChanging("Problem");
                _Problem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Problem");
                OnProblemChanged();
            }
        }
        private global::System.String _Problem;
        partial void OnProblemChanging(global::System.String value);
        partial void OnProblemChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Problems", "ODS_Journals")]
        public EntityCollection<ODS_Journals> ODS_Journals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Problems", "ODS_Journals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Problems", "ODS_Journals", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ODS_Model", Name="ODS_Roles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ODS_Roles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ODS_Roles object.
        /// </summary>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="role">Initial value of the Role property.</param>
        public static ODS_Roles CreateODS_Roles(global::System.Int32 roleId, global::System.String role)
        {
            ODS_Roles oDS_Roles = new ODS_Roles();
            oDS_Roles.RoleId = roleId;
            oDS_Roles.Role = role;
            return oDS_Roles;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Users_ODS_Roles", "ODS_Users")]
        public EntityCollection<ODS_Users> ODS_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ODS_Users>("ODS_Model.FK_ODS_Users_ODS_Roles", "ODS_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ODS_Users>("ODS_Model.FK_ODS_Users_ODS_Roles", "ODS_Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ODS_Model", Name="ODS_Uchs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ODS_Uchs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ODS_Uchs object.
        /// </summary>
        /// <param name="uchId">Initial value of the UchId property.</param>
        /// <param name="uchName">Initial value of the UchName property.</param>
        public static ODS_Uchs CreateODS_Uchs(global::System.Int32 uchId, global::System.String uchName)
        {
            ODS_Uchs oDS_Uchs = new ODS_Uchs();
            oDS_Uchs.UchId = uchId;
            oDS_Uchs.UchName = uchName;
            return oDS_Uchs;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UchId
        {
            get
            {
                return _UchId;
            }
            set
            {
                if (_UchId != value)
                {
                    OnUchIdChanging(value);
                    ReportPropertyChanging("UchId");
                    _UchId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UchId");
                    OnUchIdChanged();
                }
            }
        }
        private global::System.Int32 _UchId;
        partial void OnUchIdChanging(global::System.Int32 value);
        partial void OnUchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UchName
        {
            get
            {
                return _UchName;
            }
            set
            {
                OnUchNameChanging(value);
                ReportPropertyChanging("UchName");
                _UchName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UchName");
                OnUchNameChanged();
            }
        }
        private global::System.String _UchName;
        partial void OnUchNameChanging(global::System.String value);
        partial void OnUchNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Address_ODS_Uchs", "ODS_Address")]
        public EntityCollection<ODS_Address> ODS_Address
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ODS_Address>("ODS_Model.FK_ODS_Address_ODS_Uchs", "ODS_Address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ODS_Address>("ODS_Model.FK_ODS_Address_ODS_Uchs", "ODS_Address", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ODS_Model", Name="ODS_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ODS_Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ODS_Users object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="fIO">Initial value of the FIO property.</param>
        public static ODS_Users CreateODS_Users(global::System.Int32 userId, global::System.Int32 roleId, global::System.String login, global::System.String password, global::System.String fIO)
        {
            ODS_Users oDS_Users = new ODS_Users();
            oDS_Users.UserId = userId;
            oDS_Users.RoleId = roleId;
            oDS_Users.Login = login;
            oDS_Users.Password = password;
            oDS_Users.FIO = fIO;
            return oDS_Users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIO
        {
            get
            {
                return _FIO;
            }
            set
            {
                OnFIOChanging(value);
                ReportPropertyChanging("FIO");
                _FIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FIO");
                OnFIOChanged();
            }
        }
        private global::System.String _FIO;
        partial void OnFIOChanging(global::System.String value);
        partial void OnFIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MonterFIO
        {
            get
            {
                return _MonterFIO;
            }
            set
            {
                OnMonterFIOChanging(value);
                ReportPropertyChanging("MonterFIO");
                _MonterFIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MonterFIO");
                OnMonterFIOChanged();
            }
        }
        private global::System.String _MonterFIO;
        partial void OnMonterFIOChanging(global::System.String value);
        partial void OnMonterFIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MonterPhone
        {
            get
            {
                return _MonterPhone;
            }
            set
            {
                OnMonterPhoneChanging(value);
                ReportPropertyChanging("MonterPhone");
                _MonterPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MonterPhone");
                OnMonterPhoneChanged();
            }
        }
        private global::System.String _MonterPhone;
        partial void OnMonterPhoneChanging(global::System.String value);
        partial void OnMonterPhoneChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Users_ODS_Roles", "ODS_Roles")]
        public ODS_Roles ODS_Roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Roles>("ODS_Model.FK_ODS_Users_ODS_Roles", "ODS_Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Roles>("ODS_Model.FK_ODS_Users_ODS_Roles", "ODS_Roles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ODS_Roles> ODS_RolesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ODS_Roles>("ODS_Model.FK_ODS_Users_ODS_Roles", "ODS_Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ODS_Roles>("ODS_Model.FK_ODS_Users_ODS_Roles", "ODS_Roles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ODS_Model", "FK_ODS_Journals_ODS_Users", "ODS_Journals")]
        public EntityCollection<ODS_Journals> ODS_Journals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Users", "ODS_Journals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ODS_Journals>("ODS_Model.FK_ODS_Journals_ODS_Users", "ODS_Journals", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
